### YamlMime:ManagedReference
items:
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration
  commentId: T:OsuSharp.Interfaces.IOsuSharpConfiguration
  id: IOsuSharpConfiguration
  parent: OsuSharp.Interfaces
  children:
  - OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey
  - OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient
  - OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel
  - OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests
  - OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator
  - OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests
  - OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval
  langs:
  - csharp
  - vb
  name: IOsuSharpConfiguration
  nameWithType: IOsuSharpConfiguration
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration
  type: Interface
  source:
    id: IOsuSharpConfiguration
    path: ''
    startLine: 3195
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  syntax:
    content: public interface IOsuSharpConfiguration
    content.vb: Public Interface IOsuSharpConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey
  commentId: P:OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey
  id: ApiKey
  parent: OsuSharp.Interfaces.IOsuSharpConfiguration
  langs:
  - csharp
  - vb
  name: ApiKey
  nameWithType: IOsuSharpConfiguration.ApiKey
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey
  type: Property
  source:
    id: ApiKey
    path: ''
    startLine: 3200
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  summary: "\nYour Osu API key (required)\n"
  example: []
  syntax:
    content: string ApiKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property ApiKey As String
  overload: OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey*
  modifiers.csharp:
  - get
  - set
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator
  commentId: P:OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator
  id: ModsSeparator
  parent: OsuSharp.Interfaces.IOsuSharpConfiguration
  langs:
  - csharp
  - vb
  name: ModsSeparator
  nameWithType: IOsuSharpConfiguration.ModsSeparator
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator
  type: Property
  source:
    id: ModsSeparator
    path: ''
    startLine: 3205
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  summary: "\nSeparator between each mod on Mods property (defaults to empty)\n"
  example: []
  syntax:
    content: string ModsSeparator { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property ModsSeparator As String
  overload: OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator*
  modifiers.csharp:
  - get
  - set
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient
  commentId: P:OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient
  id: CustomHttpClient
  parent: OsuSharp.Interfaces.IOsuSharpConfiguration
  langs:
  - csharp
  - vb
  name: CustomHttpClient
  nameWithType: IOsuSharpConfiguration.CustomHttpClient
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient
  type: Property
  source:
    id: CustomHttpClient
    path: ''
    startLine: 3210
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  summary: "\nCustom http client (facultative)\n"
  example: []
  syntax:
    content: HttpClient CustomHttpClient { get; set; }
    parameters: []
    return:
      type: HttpClient
    content.vb: Property CustomHttpClient As HttpClient
  overload: OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient*
  modifiers.csharp:
  - get
  - set
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests
  commentId: P:OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests
  id: MaxRequests
  parent: OsuSharp.Interfaces.IOsuSharpConfiguration
  langs:
  - csharp
  - vb
  name: MaxRequests
  nameWithType: IOsuSharpConfiguration.MaxRequests
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests
  type: Property
  source:
    id: MaxRequests
    path: ''
    startLine: 3215
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  summary: "\nMax requests you can perform to the api. (defaults to 1200)\n"
  example: []
  syntax:
    content: int MaxRequests { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Property MaxRequests As Integer
  overload: OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests*
  modifiers.csharp:
  - get
  - set
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval
  commentId: P:OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval
  id: TimeInterval
  parent: OsuSharp.Interfaces.IOsuSharpConfiguration
  langs:
  - csharp
  - vb
  name: TimeInterval
  nameWithType: IOsuSharpConfiguration.TimeInterval
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval
  type: Property
  source:
    id: TimeInterval
    path: ''
    startLine: 3220
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  summary: "\nTime interval in which you can perform your MaxRequests. (defaults to 1 minute)\n"
  example: []
  syntax:
    content: TimeSpan TimeInterval { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Property TimeInterval As TimeSpan
  overload: OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval*
  modifiers.csharp:
  - get
  - set
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests
  commentId: P:OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests
  id: ThrowOnMaxRequests
  parent: OsuSharp.Interfaces.IOsuSharpConfiguration
  langs:
  - csharp
  - vb
  name: ThrowOnMaxRequests
  nameWithType: IOsuSharpConfiguration.ThrowOnMaxRequests
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests
  type: Property
  source:
    id: ThrowOnMaxRequests
    path: ''
    startLine: 3225
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  summary: "\nDoes the handler must throw when you&apos;re being rate-limited? (defaults to false)\n"
  example: []
  syntax:
    content: bool ThrowOnMaxRequests { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property ThrowOnMaxRequests As Boolean
  overload: OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests*
  modifiers.csharp:
  - get
  - set
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel
  commentId: P:OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel
  id: LogLevel
  parent: OsuSharp.Interfaces.IOsuSharpConfiguration
  langs:
  - csharp
  - vb
  name: LogLevel
  nameWithType: IOsuSharpConfiguration.LogLevel
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel
  type: Property
  source:
    id: LogLevel
    path: ''
    startLine: 3230
  assemblies:
  - cs.temp.dll
  namespace: OsuSharp.Interfaces
  summary: "\nLevel of the log to fire the event. (defaults to LoggingLevel.Info)\n"
  example: []
  syntax:
    content: LoggingLevel LogLevel { get; set; }
    parameters: []
    return:
      type: OsuSharp.Misc.LoggingLevel
    content.vb: Property LogLevel As LoggingLevel
  overload: OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel*
  modifiers.csharp:
  - get
  - set
references:
- uid: OsuSharp.Interfaces
  commentId: N:OsuSharp.Interfaces
  name: OsuSharp.Interfaces
  nameWithType: OsuSharp.Interfaces
  fullName: OsuSharp.Interfaces
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey*
  commentId: Overload:OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey
  name: ApiKey
  nameWithType: IOsuSharpConfiguration.ApiKey
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.ApiKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator*
  commentId: Overload:OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator
  name: ModsSeparator
  nameWithType: IOsuSharpConfiguration.ModsSeparator
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.ModsSeparator
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient*
  commentId: Overload:OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient
  name: CustomHttpClient
  nameWithType: IOsuSharpConfiguration.CustomHttpClient
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.CustomHttpClient
- uid: HttpClient
  isExternal: true
  name: HttpClient
  nameWithType: HttpClient
  fullName: HttpClient
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests*
  commentId: Overload:OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests
  name: MaxRequests
  nameWithType: IOsuSharpConfiguration.MaxRequests
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.MaxRequests
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval*
  commentId: Overload:OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval
  name: TimeInterval
  nameWithType: IOsuSharpConfiguration.TimeInterval
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.TimeInterval
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests*
  commentId: Overload:OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests
  name: ThrowOnMaxRequests
  nameWithType: IOsuSharpConfiguration.ThrowOnMaxRequests
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.ThrowOnMaxRequests
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel*
  commentId: Overload:OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel
  name: LogLevel
  nameWithType: IOsuSharpConfiguration.LogLevel
  fullName: OsuSharp.Interfaces.IOsuSharpConfiguration.LogLevel
- uid: OsuSharp.Misc.LoggingLevel
  commentId: T:OsuSharp.Misc.LoggingLevel
  parent: OsuSharp.Misc
  name: LoggingLevel
  nameWithType: LoggingLevel
  fullName: OsuSharp.Misc.LoggingLevel
- uid: OsuSharp.Misc
  commentId: N:OsuSharp.Misc
  name: OsuSharp.Misc
  nameWithType: OsuSharp.Misc
  fullName: OsuSharp.Misc
